import { ArrowRight, Check, Clock3, HandHeart, MapPin, PackageCheck, Search, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { startLogin } from "@/const";

const steps = [
  { icon: HandHeart, number: "01", title: "Share what is ready", copy: "Add the food, the quantity, and the time it needs to move. Honest details make good deliverys possible." },
  { icon: Search, number: "02", title: "Find the right next table", copy: "Nearby organizations can see offers that fit their community, kitchen, and current capacity." },
  { icon: MapPin, number: "03", title: "Arrange the delivery", copy: "Choose self-collection, a volunteer, or a real pickup hub when one is available." },
  { icon: PackageCheck, number: "04", title: "Confirm the moment", copy: "Pickup and delivery updates keep the loop visible. Completion creates a Delivery Record for everyone." },
];

export default function HowItWorks() {
  return <div className="public-page"><header className="site-header"><div className="shell header-inner"><Link href="/" className="brand-mark"><span className="brand-loop"><span /></span><span className="brand-name">Food<span>Share</span></span></Link><Link href="/" className="button button-dark button-small">Back home</Link></div></header><main>
    <section className="subpage-hero"><div className="shell narrow-copy"><p className="eyebrow"><span className="eyebrow-dot" /> A clearer way to share</p><h1>The process is simple. <em>The care is shared.</em></h1><p>Good food moves best when everyone can see what happens next. FoodShare turns a small moment of surplus into a visible chain of care.</p></div></section>
    <section className="section-pad steps-section"><div className="shell"><div className="center-heading"><p className="eyebrow">Share → Match → Collect → Deliver → Confirm</p><h2>Every delivery has a <em>next step.</em></h2></div><div className="steps-grid">{steps.map(({ icon: Icon, number, title, copy }) => <article className="step-card" key={number}><span className="step-number">{number}</span><span className="step-icon"><Icon size={22} /></span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section-pad guidance-section"><div className="shell guidance-grid"><div><p className="eyebrow">Before you share</p><h2>Good details make <em>good neighbors.</em></h2><p className="section-copy">Tell the next person what you would want to know: how it was stored, when it was prepared, what it contains, and when it needs to be collected.</p></div><div className="guidance-card"><div className="guidance-row"><Check size={17} /><span>Ready time and best-before time</span></div><div className="guidance-row"><Check size={17} /><span>Storage and serving notes</span></div><div className="guidance-row"><Check size={17} /><span>Common allergens, when known</span></div><div className="guidance-row"><Check size={17} /><span>A pickup point someone can find</span></div><div className="guidance-foot"><ShieldCheck size={18} /><span>FoodShare helps coordinate the delivery. It does not certify food safety.</span></div></div></div></section>
    <section className="section-pad window-section"><div className="shell window-story"><div className="window-story-copy"><p className="eyebrow">The Expiry Window</p><h2>A little urgency. <em>Never guesswork.</em></h2><p>Offers surface with the timing they were given. The platform never invents distance, freshness, or impact. When there is no information, it says so.</p><div className="window-callout"><Clock3 size={18} /><span>“This offer needs a delivery soon.”</span></div></div><div className="big-window"><div className="big-window-top"><span>ready</span><strong>best before</strong></div><div className="big-window-line"><span className="big-window-fill" /><i /></div><div className="big-window-bottom"><span>comfortable</span><span>plan soon</span><span>rescue now</span></div></div></div></section>
    <section className="closing-section"><div className="shell closing-inner"><div><p className="eyebrow eyebrow-light">The next moment is yours</p><h2>Choose your <em>role.</em></h2></div><Link href="/register" className="button button-apricot button-large">Join FoodShare <ArrowRight size={18} /></Link></div></section>
  </main><footer className="site-footer"><div className="shell footer-inner"><span>© 2026 FoodShare</span><Link href="/">Back to home</Link></div></footer></div>;
}
